### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'replace_with'

### ISSUE THREAD

**Issue by seehat** [kevindurston21/YANOM-Note-O-Matic#68]
**Describe the bug**
I get an error when running Yanom to convert nsx and with obsidian mode.

```bash
Processing 'Print' Notebook
|▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▍⚠                    | (!) 6/13 [46%] in 0.3s (17.19/s)
Time taken: 5.90 seconds
Unhandled exception
Traceback (most recent call last):
  File "yanom.py", line 160, in <module>
  File "yanom.py", line 129, in main
  File "yanom.py", line 143, in run_yanom
  File "notes_converter.py", line 53, in convert_notes
  File "notes_converter.py", line 114, in convert_nsx
  File "notes_converter.py", line 119, in process_nsx_files
  File "nsx_file_converter.py", line 71, in process_nsx_file
  File "nsx_file_converter.py", line 274, in process_notebooks
  File "sn_notebook.py", line 39, in process_notebook_pages
  File "sn_note_page.py", line 93, in process_note
  File "sn_note_page.py", line 150, in pre_process_content
  File "nsx_pre_processing.py", line 71, in pre_process_note_page
  File "nsx_pre_processing.py", line 164, in _fix_check_lists
  File "checklist_processing.py", line 77, in __init__
  File "checklist_processing.py", line 286, in _checklist_pre_processing
  File "checklist_processing.py", line 172, in _pre_process_html_tags
  File "checklist_processing.py", line 238, in update_tags
AttributeError: 'NoneType' object has no attribute 'replace_with'
[58952] Failed to execute script 'yanom' due to unhandled exception!
```

**To Reproduce**
1. Run yanom on nsx file with multipe notebooks.  

**Expected behavior**
Finishing the converting process. 

**Desktop (please complete the following information):**
 - OS: macOS 11.6 on Apple M1 Macbook Air

**Comment by kevindurston21** [comment]
Hi,

I just had a look.  The only way I can reproduce that failure is for a note page to be empty except for having one empty checklist item AND no content after it except a carriage return. (an empty checklist item and no further carriage returns still works)

ALSO  I could only get the failure only when stepping through the code in debugger mode in PyCharm.  The released built version works and running code without debugger works on Intel mac.  Very Odd, especially if I look at the code it reads like we should get the failure seen for empty list on empty page.

I have to say with python is sometimes a mystery as to something it works or not and perhaps there is something going on between intel and M1 mac python interpreters... one of many python mysteries.

I have uploaded a v1.5.1 release with this fix.  Can you try it out and let me know if it works.  If it does not I may need a copy of the nsx file to look at the raw pages to see if there is something else going on.

Thanks

Kevin

**Comment by seehat** [comment]
Wow, it's working now. Thank you so much. I appreciate you for solving this so fast.
