### ISSUE TITLE
UnicodeDecodeError raised in codecs.py

### ISSUE THREAD

**Issue by Loncor** [kevindurston21/YANOM-Note-O-Matic#72]
**Describe the bug**
UnicodeDecodeError was raised. Looking at the log seemed to be after completion, which was curious.

**To Reproduce**
Seems to be at the end of processing as all the notes were created in the folder.

**Expected behavior**
Would expect nothing to be raised.

**Screenshots**
Below is a copy of the error:-
2022-07-27 08:12:10,119 - INFO - YANOM.notes_converter.NotesConvertor - Time taken: 56.21 seconds
2022-07-27 08:12:10,229 - CRITICAL - root - Unhandled exception
Traceback (most recent call last):
  File "yanom.py", line 171, in <module>
  File "yanom.py", line 140, in main
  File "yanom.py", line 154, in run_yanom
  File "notes_converter.py", line 78, in convert_notes
  File "notes_converter.py", line 226, in convert_nsx
  File "notes_converter.py", line 261, in check_nsx_attachment_links
  File "notes_converter.py", line 268, in _nsx_attachment_checks
  File "pathlib.py", line 1256, in read_text
  File "codecs.py", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 10: invalid continuation byte

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version YANOM ver 1.7.0

**Additional context**
I did download the code and looked at where the error was. Thought about adding code to handle the exception but not how it was caused as I could not figure out what note was being processed as they were all created.

PS Although fairly new to python I was a professional programmer. I was impressed by how well-written the code is.

**Comment by kevindurston21** [comment]
Hi,

Thanks for the comment on the code.. still a lot of tidying up I'd like to get around to :-)

Had a quick first look at this problem over breakfast.... It's a weird one as usual...

1. converted content is written with UTF-8 encoding....
2. written content is then read using UTF-8 encoding...
3. Raises error suggesting content is not UTF-8...

Head scratching time!  Will do some testing and look for a solution.

Cheers,

Kevin

**Comment by ledhed2222** [comment]
I've encountered a similar (but not identical) issue. I think it's related as it's happening at the same time in the process. The data in the error is different, however:

```
Analysing note page links
|⚠                                       | (!) 0/1 [0%] in 0.1s (0.00/s)
Unhandled exception
Traceback (most recent call last):
  File "yanom.py", line 171, in <module>
  File "yanom.py", line 140, in main
  File "yanom.py", line 154, in run_yanom
  File "notes_converter.py", line 78, in convert_notes
  File "notes_converter.py", line 226, in convert_nsx
  File "notes_converter.py", line 261, in check_nsx_attachment_links
  File "notes_converter.py", line 268, in _nsx_attachment_checks
  File "pathlib.py", line 1256, in read_text
  File "codecs.py", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 11: invalid start byte
[94457] Failed to execute script 'yanom' due to unhandled exception!
```

**Comment by ledhed2222** [comment]
Also, could you please add a CONTRIBUTING doc? I wanted to run from source so that I could print the offending file name here, but couldn't get this repo to build after a few attempts and gave up. Would be happy to fix this issue if I knew how to build/run locally (macOS) :)

**Comment by ledhed2222** [comment]
I opened a PR that I think will help with this, but it's not perfect. It just allows users to skip the offending checks:

https://github.com/kevindurston21/YANOM-Note-O-Matic/pull/82/files
