### ISSUE TITLE
Nimbus converter tuple index out of range

### ISSUE THREAD

**Issue by holligram** [kevindurston21/YANOM-Note-O-Matic#73]
**Describe the bug**
receive a tuple index out of range in nimbus_converter.py (see error .log contents below)

**To Reproduce**
running the latest win10 release 1.7.0
numbus to obsidian against a fresh export from Nimbus 10.0.54

**Desktop (please complete the following information):**
 - OS: win10

**Additional context**
error.log contains:
2022-10-15 15:29:55,766 - CRITICAL - root - Unhandled exception
Traceback (most recent call last):
  File "yanom.py", line 171, in <module>
  File "yanom.py", line 140, in main
  File "yanom.py", line 154, in run_yanom
  File "notes_converter.py", line 78, in convert_notes
  File "notes_converter.py", line 236, in convert_nimbus
  File "nimbus_converter.py", line 226, in convert_nimbus_notes
  File "nimbus_converter.py", line 256, in extract_note_content
  File "nimbus_converter.py", line 163, in initialise_new_note
IndexError: tuple index out of range

**Comment by mochell** [comment]
the same issue appears under OSX 11.3.
