### ISSUE TITLE
OSError: [Errno 63] File name too long

### ISSUE THREAD

**Issue by cukabeka** [kevindurston21/YANOM-Note-O-Matic#75]
**Describe the bug**

**To Reproduce**
1. Create a NSX Note with a extremely long name (+255 char). I'ts possible that NoteStation does not cut long texts if they were entered directly at the beginning with no CarriageReturn
2. Export NSX
3. Use YANOM 

**Expected behavior**
Just cuts the length of the filename

**Screenshots**
```
CRITICAL - root - Unhandled exception
Traceback (most recent call last):
  File "yanom.py", line 171, in <module>
  File "yanom.py", line 140, in main
  File "yanom.py", line 154, in run_yanom
  File "notes_converter.py", line 78, in convert_notes
  File "notes_converter.py", line 222, in convert_nsx
  File "pandoc_converter.py", line 36, in __init__
  File "pandoc_converter.py", line 62, in check_and_set_pandoc_options_if_required
  File "pandoc_converter.py", line 67, in find_pandoc_version
  File "subprocess.py", line 503, in run
  File "subprocess.py", line 1130, in communicate
  File "subprocess.py", line 1978, in _communicate
  File "subprocess.py", line 1174, in _check_timeout
subprocess.TimeoutExpired: Command '['/Users/me/yanom-v1.7.0/pandoc/pandoc', '-v']' timed out after 3 seconds

CRITICAL - root - Unhandled exception
Traceback (most recent call last):
  File "yanom.py", line 171, in <module>
  File "yanom.py", line 140, in main
  File "yanom.py", line 154, in run_yanom
  File "notes_converter.py", line 78, in convert_notes
  File "notes_converter.py", line 225, in convert_nsx
  File "notes_converter.py", line 246, in process_nsx_files
  File "nsx_file_converter.py", line 75, in process_nsx_file
  File "nsx_file_converter.py", line 110, in generate_note_page_filename_and_path
  File "sn_note_page.py", line 141, in generate_filenames_and_paths
  File "sn_note_page.py", line 135, in _generate_absolute_path
  File "helper_functions.py", line 351, in find_valid_full_file_path
  File "pathlib.py", line 1407, in exists
  File "pathlib.py", line 1221, in stat
OSError: [Errno 63] File name too long: '/Users/me/Notes/ReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameernReallylongnameern.gfjscn.md'

[34688] Failed to execute script 'yanom' due to unhandled exception!

```

**Desktop (please complete the following information):**
 - OS: MacOS 13.1

**Comment by cukabeka** [comment]
I also tried to set
`max_file_or_directory_name_length = 64`
in the ini file, but with no success.

**Comment by cukabeka** [comment]
I tried manual mode as well, with no success again.

**Comment by Mehonoshin** [comment]
Same stuff for me, have to fix all long titles manually

**Comment by paradeiser** [comment]
+1
